fix type drop to cascade (#393)
if you have function or operator with  type which is removed, you will have error

error: cannot drop type because other objects depend on it