fix type drop to cascade
if you have function or operator with  type which is removed, you will have error

error: cannot drop type because other objects depend on it